dist: trusty
sudo: false

env:
  global:
   - XGBOOST_VERSION=0.7
   - DMLC_CORE_COMMIT_HASH=2777ad99d823848cbce6354688b397d519f7b810

language: java
jdk:
  - oraclejdk7
# - openjdk7

# Caching so the next build will be fast too.
cache:
  apt: true
  directories:
    - $HOME/.m2
    - $HOME/Library/Caches/Homebrew

matrix:
  include:
    - os: linux
      sudo: required
      group: edge
      services:
        - docker
    - os: osx
      osx_image: xcode8

notifications:
  email: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      apt-get update;
    fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew install gcc49 --without-multilib;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        apt-get install -y git g++-4.7 openjdk-7-jdk make;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        export JAVA_HOME=`/usr/libexec/java_home -v 1.7`;
        CC=`which gcc-4.9` CXX=`which g++-4.9` sh scripts/build.sh;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        export JAVA_HOME=/usr/lib/jvm/java-8-oracle;
        CC=`which gcc-4.7` CXX=`which g++-4.7` sh scripts/build.sh;
    fi

deploy:
  provider: releases
  api_key:
    secure: 4b6603199a344a7596bfdb53e801a5b42795c58a
  file:
    - xgboost4j-$XGBOOST_VERSION-$TRAVIS_OS_NAME.jar
  skip_cleanup: true # do not delete the built assets
  overwrite: true
  on:
    tags: true
