sudo: false
group: deprecated-2017Q4

env:
  global:
   - XGBOOST_VERSION=0.7
   - DMLC_CORE_COMMIT_HASH=2777ad99d823848cbce6354688b397d519f7b810

language: java
jdk:
  - openjdk7

# Caching so the next build will be fast too.
cache:
  apt: true
  directories:
    - $HOME/.m2
    - $HOME/Library/Caches/Homebrew

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      group: edge
      services:
        - docker
    - os: osx
      osx_image: xcode8

notifications:
  email: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get -y install software-properties-common;
        sudo add-apt-repository -y ppa:george-edison55/cmake-3.x;
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
        sudo apt-get update;
    fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew install gcc49 --without-multilib;
        brew install cmake;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get install -y git g++-4.9 make cmake;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        CC=`which gcc-4.9` CXX=`which g++-4.9` sh scripts/build.sh;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        CC=`which gcc-4.7` CXX=`which g++-4.9` sh scripts/build.sh;
    fi

deploy:
  provider: releases
  api_key:
    secure: QhpgTqzNOcd9nynyQJ6LiKECezwRZaFqSHPb5fTGKdn98MF+7pAFW4ta2kbg3pyPqCjlzTexKdU0Ro3QyWsvzZ1ss5l1gQm1r7D0ELj0foobW62M3Niu7uhxGharMSgIyO0mTWh3+XgOGZU8/v0N8G/FMiGpBmDv2Vn/dK3atDVkfjCYZBst7Nkqavn0m1OuqOkhE4JM4SOFhTnn5AsiNO46hRSn0R6kVH9Ynmxyd7KcAH8MBDfOBuJd/BsYgJhpt5MYS2xGYHB/93Dgiz/9gM643+KKfY94BvMtG8NGLYhci7/UuQng4/NKTo8ptviGCqgMxnSO55ddjFHIIHPTdHv0j8pn7s9XLk8kmIr9HRdudYsJDRXu/C/zz3t7qqQsVpQ/TAe2+wFLDppdaMpIpX8vJ3mPNzP5ICA7o040bB/S5bfvs6Y5S9w6zIYEXlNbg+FvLYwXI42H2g57dQ7IOhwB8okWQK0GEZMOBHvcM3c7Oyh+Gdn7lwI+XEcAgLEGqspnWXTbD7mXQTiVFyLomUkjvzACwxHVu+qCyssR+XtlFoMj2Syl9laqN9C1sPTvIj/enO3emypzpJXhg4+xISVM8Hi2hxRSyiAl0fGx9v77nZkYnvvel+QKlJfiKC6bnNKQkvnVo9W3VJY3V0sXFEa/iv+fmc9bFQPlZJ6LXK4=
  file:
    - xgboost4j-$XGBOOST_VERSION-$TRAVIS_OS_NAME.jar
  on:
    repo: myui/build-xgboost-jvm
  skip_cleanup: true # do not delete the built assets
  overwrite: true
  on:
    tags: true

